package bwapi

// techTypeData holds static properties for a TechType.
type techTypeData struct {
	mineralPrice   int
	gasPrice       int
	researchTime   int
	energyCost     int
	whatResearches UnitType
	race           Race
	weaponType     WeaponType
}

// techTypeTable is a lookup table of static tech type data, indexed by TechType ID.
// Populated from fullTechTypeTable (generated by gen_tech_types.py).
var techTypeTable [47]techTypeData

func init() {
	for i, d := range fullTechTypeTable {
		techTypeTable[i] = techTypeData{
			mineralPrice:   int(d.mineralPrice),
			gasPrice:       int(d.gasPrice),
			researchTime:   int(d.researchTime),
			energyCost:     int(d.energyCost),
			whatResearches: UnitType(d.whatResearches),
			race:           Race(d.race),
			weaponType:     WeaponType(d.weaponType),
		}
	}
}

func ttInRange(tt TechType) bool {
	return tt >= 0 && int(tt) < len(techTypeTable)
}

// MineralPrice returns the mineral cost to research this technology.
func (tt TechType) MineralPrice() int {
	if !ttInRange(tt) {
		return 0
	}
	return techTypeTable[tt].mineralPrice
}

// GasPrice returns the vespene gas cost to research this technology.
func (tt TechType) GasPrice() int {
	if !ttInRange(tt) {
		return 0
	}
	return techTypeTable[tt].gasPrice
}

// ResearchTime returns the number of frames needed to research this technology.
func (tt TechType) ResearchTime() int {
	if !ttInRange(tt) {
		return 0
	}
	return techTypeTable[tt].researchTime
}

// EnergyCost returns the energy cost to use this technology.
func (tt TechType) EnergyCost() int {
	if !ttInRange(tt) {
		return 0
	}
	return techTypeTable[tt].energyCost
}

// WhatResearches returns the UnitType that can research this technology.
func (tt TechType) WhatResearches() UnitType {
	if !ttInRange(tt) {
		return UnitTypeNone
	}
	return techTypeTable[tt].whatResearches
}

// GetRace returns the Race that this technology belongs to.
func (tt TechType) GetRace() Race {
	if !ttInRange(tt) {
		return RaceNone
	}
	return techTypeTable[tt].race
}

// GetWeaponType returns the WeaponType associated with this technology.
func (tt TechType) GetWeaponType() WeaponType {
	if !ttInRange(tt) {
		return WeaponTypeNone
	}
	return techTypeTable[tt].weaponType
}
