package bwapi

// unitTypeData holds static properties for a UnitType.
type unitTypeData struct {
	dimensionLeft, dimensionRight, dimensionUp, dimensionDown int
	tileWidth, tileHeight                                     int
	isFlyer, isBuilding, isWorker                             bool
	isSpell, isMineralField, isRefinery                       bool
	isResourceContainer, isResourceDepot                      bool
	spaceRequired, spaceProvided                              int
	groundWeapon, airWeapon                                   WeaponType
	seekRange, sightRange                                     int
	maxHitPoints, maxShields, maxEnergy, armor                int
}

// unitTypeTable is a lookup table of static unit type data, indexed by UnitType ID.
// Populated from fullUnitTypeTable (generated by gen_unit_types.py) with manual overrides.
var unitTypeTable [234]unitTypeData

func init() {
	for i, d := range fullUnitTypeTable {
		unitTypeTable[i] = unitTypeData{
			dimensionLeft:       int(d.dimensionLeft),
			dimensionRight:      int(d.dimensionRight),
			dimensionUp:         int(d.dimensionUp),
			dimensionDown:       int(d.dimensionDown),
			tileWidth:           int(d.tileWidth),
			tileHeight:          int(d.tileHeight),
			isFlyer:             d.isFlyer,
			isBuilding:          d.isBuilding,
			isWorker:            d.isWorker,
			isSpell:             d.isSpell,
			isMineralField:      d.isMineralField,
			isResourceContainer: d.isResourceContainer,
			isResourceDepot:     d.isResourceDepot,
			spaceRequired:       int(d.spaceRequired),
			spaceProvided:       int(d.spaceProvided),
			groundWeapon:        d.groundWeapon,
			airWeapon:           d.airWeapon,
			seekRange:           int(d.seekRange),
			sightRange:          int(d.sightRange),
			maxHitPoints:        int(d.maxHitPoints),
			maxShields:          int(d.maxShields),
			maxEnergy:           int(d.maxEnergy),
			armor:               int(d.armor),
		}
	}
	// isRefinery is not tracked in the generated table; set manually.
	unitTypeTable[UnitTypeTerranRefinery].isRefinery = true
	unitTypeTable[UnitTypeProtossAssimilator].isRefinery = true
	unitTypeTable[UnitTypeZergExtractor].isRefinery = true
}

func utInRange(ut UnitType) bool {
	return ut >= 0 && int(ut) < len(unitTypeTable)
}

// DimensionLeft returns the pixel offset from center to the left edge.
func (ut UnitType) DimensionLeft() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].dimensionLeft
}

// DimensionRight returns the pixel offset from center to the right edge.
func (ut UnitType) DimensionRight() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].dimensionRight
}

// DimensionUp returns the pixel offset from center to the top edge.
func (ut UnitType) DimensionUp() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].dimensionUp
}

// DimensionDown returns the pixel offset from center to the bottom edge.
func (ut UnitType) DimensionDown() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].dimensionDown
}

// TileWidth returns the width of this building in build tiles.
func (ut UnitType) TileWidth() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].tileWidth
}

// TileHeight returns the height of this building in build tiles.
func (ut UnitType) TileHeight() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].tileHeight
}

// IsFlyer returns whether this unit type is airborne.
func (ut UnitType) IsFlyer() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isFlyer
}

// IsBuilding returns whether this unit type is a structure.
func (ut UnitType) IsBuilding() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isBuilding
}

// IsWorker returns whether this unit type is a worker.
func (ut UnitType) IsWorker() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isWorker
}

// IsSpell returns whether this unit type is a spell effect.
func (ut UnitType) IsSpell() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isSpell
}

// IsMineralField returns whether this unit type is a mineral field.
func (ut UnitType) IsMineralField() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isMineralField
}

// IsRefinery returns whether this unit type is a gas refinery.
func (ut UnitType) IsRefinery() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isRefinery
}

// IsResourceContainer returns whether this unit type contains resources (mineral fields, geysers).
func (ut UnitType) IsResourceContainer() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isResourceContainer
}

// IsResourceDepot returns whether this unit type is a resource depot (command center, hatchery, nexus).
func (ut UnitType) IsResourceDepot() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isResourceDepot
}

// SpaceRequired returns the transport space this unit requires (255 = cannot be transported).
func (ut UnitType) SpaceRequired() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].spaceRequired
}

// SpaceProvided returns the transport space this unit provides.
func (ut UnitType) SpaceProvided() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].spaceProvided
}

// GroundWeapon returns the WeaponType used against ground targets.
func (ut UnitType) GroundWeapon() WeaponType {
	if !utInRange(ut) {
		return WeaponTypeNone
	}
	return unitTypeTable[ut].groundWeapon
}

// AirWeapon returns the WeaponType used against air targets.
func (ut UnitType) AirWeapon() WeaponType {
	if !utInRange(ut) {
		return WeaponTypeNone
	}
	return unitTypeTable[ut].airWeapon
}

// SeekRange returns the range at which this unit will automatically acquire targets, in pixels.
func (ut UnitType) SeekRange() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].seekRange
}

// SightRange returns the sight range of this unit type in pixels.
func (ut UnitType) SightRange() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].sightRange
}

// MaxHitPoints returns the maximum hit points for this unit type.
func (ut UnitType) MaxHitPoints() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].maxHitPoints
}

// MaxShields returns the maximum shield points for this unit type (0 if no shields).
func (ut UnitType) MaxShields() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].maxShields
}

// MaxEnergy returns the maximum energy for this unit type (0 if not a spellcaster).
func (ut UnitType) MaxEnergy() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].maxEnergy
}

// Armor returns the base armor value for this unit type.
func (ut UnitType) Armor() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].armor
}
