package bwapi

// unitTypeData holds static properties for a UnitType.
type unitTypeData struct {
	dimensionLeft, dimensionRight, dimensionUp, dimensionDown int
	tileWidth, tileHeight                                     int
	isFlyer, isBuilding, isWorker                             bool
	isSpell, isMineralField, isRefinery                       bool
	isResourceContainer, isResourceDepot                      bool
	spaceRequired, spaceProvided                              int
	groundWeapon, airWeapon                                   WeaponType
	seekRange, sightRange                                     int
	maxHitPoints, maxShields, maxEnergy, armor                int
	whatBuildsType                                            UnitType
	whatBuildsCount                                           int
	requiredUnits                                             [4]struct{ unitType UnitType; count int }
	requiredUnitCount                                         int
	requiredTech                                              TechType
	race                                                      Race
	mineralPrice, gasPrice, buildTime                         int
	supplyRequired, supplyProvided                            int
	isTwoUnitsInOneEgg, isAddon                              bool
	requiresCreep, requiresPsi                                bool
	armorUpgrade                                              UpgradeType
	size                                                      UnitSizeType
}

// unitTypeTable is a lookup table of static unit type data, indexed by UnitType ID.
// Populated from fullUnitTypeTable (generated by gen_unit_types.py) with manual overrides.
var unitTypeTable [234]unitTypeData

func init() {
	for i, d := range fullUnitTypeTable {
		var reqUnits [4]struct{ unitType UnitType; count int }
		for j := 0; j < 4; j++ {
			reqUnits[j].unitType = UnitType(d.requiredUnits[j].unitType)
			reqUnits[j].count = int(d.requiredUnits[j].count)
		}
		unitTypeTable[i] = unitTypeData{
			dimensionLeft:       int(d.dimensionLeft),
			dimensionRight:      int(d.dimensionRight),
			dimensionUp:         int(d.dimensionUp),
			dimensionDown:       int(d.dimensionDown),
			tileWidth:           int(d.tileWidth),
			tileHeight:          int(d.tileHeight),
			isFlyer:             d.isFlyer,
			isBuilding:          d.isBuilding,
			isWorker:            d.isWorker,
			isSpell:             d.isSpell,
			isMineralField:      d.isMineralField,
			isResourceContainer: d.isResourceContainer,
			isResourceDepot:     d.isResourceDepot,
			spaceRequired:       int(d.spaceRequired),
			spaceProvided:       int(d.spaceProvided),
			groundWeapon:        d.groundWeapon,
			airWeapon:           d.airWeapon,
			seekRange:           int(d.seekRange),
			sightRange:          int(d.sightRange),
			maxHitPoints:        int(d.maxHitPoints),
			maxShields:          int(d.maxShields),
			maxEnergy:           int(d.maxEnergy),
			armor:               int(d.armor),
			whatBuildsType:      UnitType(d.whatBuildsType),
			whatBuildsCount:     int(d.whatBuildsCount),
			requiredUnits:       reqUnits,
			requiredUnitCount:   int(d.requiredUnitCount),
			requiredTech:        TechType(d.requiredTech),
			race:                Race(d.race),
			mineralPrice:        int(d.mineralPrice),
			gasPrice:            int(d.gasPrice),
			buildTime:           int(d.buildTime),
			supplyRequired:      int(d.supplyRequired),
			supplyProvided:      int(d.supplyProvided),
			isTwoUnitsInOneEgg:  d.isTwoUnitsInOneEgg,
			isAddon:             d.isAddon,
			requiresCreep:       d.requiresCreep,
			requiresPsi:         d.requiresPsi,
			armorUpgrade:        UpgradeType(d.armorUpgrade),
			size:                UnitSizeType(d.size),
		}
	}
	// isRefinery is not tracked in the generated table; set manually.
	unitTypeTable[UnitTypeTerranRefinery].isRefinery = true
	unitTypeTable[UnitTypeProtossAssimilator].isRefinery = true
	unitTypeTable[UnitTypeZergExtractor].isRefinery = true
}

func utInRange(ut UnitType) bool {
	return ut >= 0 && int(ut) < len(unitTypeTable)
}

// DimensionLeft returns the pixel offset from center to the left edge.
func (ut UnitType) DimensionLeft() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].dimensionLeft
}

// DimensionRight returns the pixel offset from center to the right edge.
func (ut UnitType) DimensionRight() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].dimensionRight
}

// DimensionUp returns the pixel offset from center to the top edge.
func (ut UnitType) DimensionUp() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].dimensionUp
}

// DimensionDown returns the pixel offset from center to the bottom edge.
func (ut UnitType) DimensionDown() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].dimensionDown
}

// TileWidth returns the width of this building in build tiles.
func (ut UnitType) TileWidth() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].tileWidth
}

// TileHeight returns the height of this building in build tiles.
func (ut UnitType) TileHeight() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].tileHeight
}

// IsFlyer returns whether this unit type is airborne.
func (ut UnitType) IsFlyer() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isFlyer
}

// IsBuilding returns whether this unit type is a structure.
func (ut UnitType) IsBuilding() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isBuilding
}

// IsWorker returns whether this unit type is a worker.
func (ut UnitType) IsWorker() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isWorker
}

// IsSpell returns whether this unit type is a spell effect.
func (ut UnitType) IsSpell() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isSpell
}

// IsMineralField returns whether this unit type is a mineral field.
func (ut UnitType) IsMineralField() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isMineralField
}

// IsRefinery returns whether this unit type is a gas refinery.
func (ut UnitType) IsRefinery() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isRefinery
}

// IsResourceContainer returns whether this unit type contains resources (mineral fields, geysers).
func (ut UnitType) IsResourceContainer() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isResourceContainer
}

// IsResourceDepot returns whether this unit type is a resource depot (command center, hatchery, nexus).
func (ut UnitType) IsResourceDepot() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isResourceDepot
}

// SpaceRequired returns the transport space this unit requires (255 = cannot be transported).
func (ut UnitType) SpaceRequired() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].spaceRequired
}

// SpaceProvided returns the transport space this unit provides.
func (ut UnitType) SpaceProvided() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].spaceProvided
}

// GroundWeapon returns the WeaponType used against ground targets.
func (ut UnitType) GroundWeapon() WeaponType {
	if !utInRange(ut) {
		return WeaponTypeNone
	}
	return unitTypeTable[ut].groundWeapon
}

// AirWeapon returns the WeaponType used against air targets.
func (ut UnitType) AirWeapon() WeaponType {
	if !utInRange(ut) {
		return WeaponTypeNone
	}
	return unitTypeTable[ut].airWeapon
}

// SeekRange returns the range at which this unit will automatically acquire targets, in pixels.
func (ut UnitType) SeekRange() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].seekRange
}

// SightRange returns the sight range of this unit type in pixels.
func (ut UnitType) SightRange() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].sightRange
}

// MaxHitPoints returns the maximum hit points for this unit type.
func (ut UnitType) MaxHitPoints() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].maxHitPoints
}

// MaxShields returns the maximum shield points for this unit type (0 if no shields).
func (ut UnitType) MaxShields() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].maxShields
}

// MaxEnergy returns the maximum energy for this unit type (0 if not a spellcaster).
func (ut UnitType) MaxEnergy() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].maxEnergy
}

// Armor returns the base armor value for this unit type.
func (ut UnitType) Armor() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].armor
}

// WhatBuilds returns the UnitType that produces this unit and the count required.
// Count is usually 1, but 2 for Archon merges. Returns (UnitTypeNone, 0) if not buildable.
func (ut UnitType) WhatBuilds() (UnitType, int) {
	if !utInRange(ut) {
		return UnitTypeNone, 0
	}
	return unitTypeTable[ut].whatBuildsType, unitTypeTable[ut].whatBuildsCount
}

// RequiredUnits returns a map of prerequisite UnitTypes and their required counts.
func (ut UnitType) RequiredUnits() map[UnitType]int {
	m := make(map[UnitType]int)
	if !utInRange(ut) {
		return m
	}
	d := &unitTypeTable[ut]
	for i := 0; i < d.requiredUnitCount; i++ {
		ru := d.requiredUnits[i]
		if ru.unitType != UnitTypeNone {
			m[ru.unitType] = ru.count
		}
	}
	return m
}

// RequiredTech returns the TechType required to build this unit.
// Returns TechTypeNone for most units.
func (ut UnitType) RequiredTech() TechType {
	if !utInRange(ut) {
		return TechTypeNone
	}
	return unitTypeTable[ut].requiredTech
}

// GetRace returns the Race of this unit type.
func (ut UnitType) GetRace() Race {
	if !utInRange(ut) {
		return RaceNone
	}
	return unitTypeTable[ut].race
}

// MineralPrice returns the mineral cost to produce this unit.
func (ut UnitType) MineralPrice() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].mineralPrice
}

// GasPrice returns the vespene gas cost to produce this unit.
func (ut UnitType) GasPrice() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].gasPrice
}

// BuildTime returns the time in frames to produce this unit.
func (ut UnitType) BuildTime() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].buildTime
}

// SupplyRequired returns the supply cost in BWAPI doubled format (2 = 1 supply).
func (ut UnitType) SupplyRequired() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].supplyRequired
}

// SupplyProvided returns the supply provided in BWAPI doubled format (16 = 8 supply).
func (ut UnitType) SupplyProvided() int {
	if !utInRange(ut) {
		return 0
	}
	return unitTypeTable[ut].supplyProvided
}

// IsTwoUnitsInOneEgg returns whether this unit type produces two units per egg (e.g., Zerglings, Scourge).
func (ut UnitType) IsTwoUnitsInOneEgg() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isTwoUnitsInOneEgg
}

// IsAddon returns whether this unit type is a building addon (e.g., Comsat Station, Machine Shop).
func (ut UnitType) IsAddon() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].isAddon
}

// RequiresCreep returns whether this building must be placed on creep.
func (ut UnitType) RequiresCreep() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].requiresCreep
}

// RequiresPsi returns whether this building requires pylon power.
func (ut UnitType) RequiresPsi() bool {
	if !utInRange(ut) {
		return false
	}
	return unitTypeTable[ut].requiresPsi
}

// ArmorUpgrade returns the UpgradeType that improves this unit's armor.
func (ut UnitType) ArmorUpgrade() UpgradeType {
	if !utInRange(ut) {
		return UpgradeTypeNone
	}
	return unitTypeTable[ut].armorUpgrade
}

// Size returns the UnitSizeType of this unit (Small, Medium, Large, etc.).
func (ut UnitType) Size() UnitSizeType {
	if !utInRange(ut) {
		return UnitSizeTypeNone
	}
	return unitTypeTable[ut].size
}

// TileSize returns the tile dimensions of this unit type as a TilePosition.
func (ut UnitType) TileSize() TilePosition {
	return TilePosition{X: int32(ut.TileWidth()), Y: int32(ut.TileHeight())}
}

// ProducesLarva returns whether this unit type produces larva (Hatchery, Lair, Hive).
func (ut UnitType) ProducesLarva() bool {
	return ut == UnitTypeZergHatchery || ut == UnitTypeZergLair || ut == UnitTypeZergHive
}

// CanBuildAddon returns whether this building type can have an addon attached.
func (ut UnitType) CanBuildAddon() bool {
	switch ut {
	case UnitTypeTerranCommandCenter, UnitTypeTerranFactory,
		UnitTypeTerranStarport, UnitTypeTerranScienceFacility,
		UnitTypeTerranBarracks:
		return true
	}
	return false
}
