package bwapi

// upgradeTypeData holds static properties for an UpgradeType.
type upgradeTypeData struct {
	mineralPriceBase   int
	mineralPriceFactor int
	gasPriceBase       int
	gasPriceFactor     int
	upgradeTimeBase    int
	upgradeTimeFactor  int
	maxRepeats         int
	whatUpgrades       UnitType
	race               Race
	whatsRequired      [3]UnitType // indexed by level-1 (0=level 1, 1=level 2, 2=level 3)
}

// upgradeTypeTable is a lookup table of static upgrade type data, indexed by UpgradeType ID.
// Populated from fullUpgradeTypeTable (generated by gen_upgrade_types.py).
var upgradeTypeTable [63]upgradeTypeData

func init() {
	for i, d := range fullUpgradeTypeTable {
		upgradeTypeTable[i] = upgradeTypeData{
			mineralPriceBase:   int(d.mineralPriceBase),
			mineralPriceFactor: int(d.mineralPriceFactor),
			gasPriceBase:       int(d.gasPriceBase),
			gasPriceFactor:     int(d.gasPriceFactor),
			upgradeTimeBase:    int(d.upgradeTimeBase),
			upgradeTimeFactor:  int(d.upgradeTimeFactor),
			maxRepeats:         int(d.maxRepeats),
			whatUpgrades:       UnitType(d.whatUpgrades),
			race:               Race(d.race),
			whatsRequired: [3]UnitType{
				UnitType(d.whatsRequired0),
				UnitType(d.whatsRequired1),
				UnitType(d.whatsRequired2),
			},
		}
	}
}

func upInRange(up UpgradeType) bool {
	return up >= 0 && int(up) < len(upgradeTypeTable)
}

// MineralPrice returns the mineral cost for a given upgrade level.
// Level should be in the range [1, MaxRepeats()].
func (up UpgradeType) MineralPrice(level int) int {
	if !upInRange(up) {
		return 0
	}
	d := &upgradeTypeTable[up]
	return d.mineralPriceBase + d.mineralPriceFactor*(level-1)
}

// GasPrice returns the vespene gas cost for a given upgrade level.
// Level should be in the range [1, MaxRepeats()].
func (up UpgradeType) GasPrice(level int) int {
	if !upInRange(up) {
		return 0
	}
	d := &upgradeTypeTable[up]
	return d.gasPriceBase + d.gasPriceFactor*(level-1)
}

// UpgradeTime returns the number of frames needed for a given upgrade level.
// Level should be in the range [1, MaxRepeats()].
func (up UpgradeType) UpgradeTime(level int) int {
	if !upInRange(up) {
		return 0
	}
	d := &upgradeTypeTable[up]
	return d.upgradeTimeBase + d.upgradeTimeFactor*(level-1)
}

// MaxRepeats returns the maximum number of times this upgrade can be researched.
func (up UpgradeType) MaxRepeats() int {
	if !upInRange(up) {
		return 0
	}
	return upgradeTypeTable[up].maxRepeats
}

// WhatUpgrades returns the UnitType that can research this upgrade.
func (up UpgradeType) WhatUpgrades() UnitType {
	if !upInRange(up) {
		return UnitTypeNone
	}
	return upgradeTypeTable[up].whatUpgrades
}

// GetRace returns the Race that this upgrade belongs to.
func (up UpgradeType) GetRace() Race {
	if !upInRange(up) {
		return RaceNone
	}
	return upgradeTypeTable[up].race
}

// WhatsRequired returns the UnitType prerequisite for a given upgrade level.
// Level should be in the range [1, MaxRepeats()].
func (up UpgradeType) WhatsRequired(level int) UnitType {
	if !upInRange(up) || level < 1 || level > 3 {
		return UnitTypeNone
	}
	return upgradeTypeTable[up].whatsRequired[level-1]
}
