package bwapi

// fullWeaponTypeData holds static data for a weapon type, indexed by WeaponType ID.
type fullWeaponTypeData struct {
	damageAmount       int32
	damageBonus        int32
	damageCooldown     int32
	damageFactor       int32
	damageType         DamageType
	explosionType      ExplosionType
	minRange           int32
	maxRange           int32
	innerSplashRadius  int32
	medianSplashRadius int32
	outerSplashRadius  int32
	targetsAir         bool
	targetsGround      bool
	upgradeType        UpgradeType
}

// fullWeaponTypeTable contains static data for all 132 BWAPI weapon types, indexed by WeaponType ID.
var fullWeaponTypeTable = [132]fullWeaponTypeData{
	// 0: Gauss_Rifle
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 1: Gauss_Rifle_Jim_Raynor
	{damageAmount: 18, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 2: C_10_Canister_Rifle
	{damageAmount: 10, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 3: C_10_Canister_Rifle_Sarah_Kerrigan
	{damageAmount: 30, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 4: Fragmentation_Grenade
	{damageAmount: 20, damageBonus: 2, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 5: Fragmentation_Grenade_Jim_Raynor
	{damageAmount: 30, damageBonus: 2, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 6: Spider_Mines
	{damageAmount: 125, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(2),
		minRange: 0, maxRange: 10,
		innerSplashRadius: 50, medianSplashRadius: 75, outerSplashRadius: 100,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 7: Twin_Autocannons
	{damageAmount: 12, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 8: Hellfire_Missile_Pack
	{damageAmount: 10, damageBonus: 2, damageCooldown: 22, damageFactor: 2,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(8)},
	// 9: Twin_Autocannons_Alan_Schezar
	{damageAmount: 24, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 10: Hellfire_Missile_Pack_Alan_Schezar
	{damageAmount: 20, damageBonus: 1, damageCooldown: 22, damageFactor: 2,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(8)},
	// 11: Arclite_Cannon
	{damageAmount: 30, damageBonus: 3, damageCooldown: 37, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 12: Arclite_Cannon_Edmund_Duke
	{damageAmount: 70, damageBonus: 3, damageCooldown: 37, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 13: Fusion_Cutter
	{damageAmount: 5, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 10,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 14: (skipped)
	{damageAmount: 0, damageBonus: 0, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(0),
		minRange: 0, maxRange: 10,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 15: Gemini_Missiles
	{damageAmount: 20, damageBonus: 2, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(9)},
	// 16: Burst_Lasers
	{damageAmount: 8, damageBonus: 1, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(9)},
	// 17: Gemini_Missiles_Tom_Kazansky
	{damageAmount: 40, damageBonus: 2, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(9)},
	// 18: Burst_Lasers_Tom_Kazansky
	{damageAmount: 16, damageBonus: 1, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(9)},
	// 19: ATS_Laser_Battery
	{damageAmount: 25, damageBonus: 3, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(9)},
	// 20: ATA_Laser_Battery
	{damageAmount: 25, damageBonus: 3, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(9)},
	// 21: ATS_Laser_Battery_Hero
	{damageAmount: 50, damageBonus: 3, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(9)},
	// 22: ATA_Laser_Battery_Hero
	{damageAmount: 50, damageBonus: 3, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(9)},
	// 23: ATS_Laser_Battery_Hyperion
	{damageAmount: 30, damageBonus: 3, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(9)},
	// 24: ATA_Laser_Battery_Hyperion
	{damageAmount: 30, damageBonus: 3, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(9)},
	// 25: Flame_Thrower
	{damageAmount: 8, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(3),
		minRange: 0, maxRange: 32,
		innerSplashRadius: 15, medianSplashRadius: 20, outerSplashRadius: 25,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 26: Flame_Thrower_Gui_Montag
	{damageAmount: 16, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(3),
		minRange: 0, maxRange: 32,
		innerSplashRadius: 15, medianSplashRadius: 20, outerSplashRadius: 25,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 27: Arclite_Shock_Cannon
	{damageAmount: 70, damageBonus: 5, damageCooldown: 75, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(2),
		minRange: 64, maxRange: 384,
		innerSplashRadius: 10, medianSplashRadius: 25, outerSplashRadius: 40,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 28: Arclite_Shock_Cannon_Edmund_Duke
	{damageAmount: 150, damageBonus: 5, damageCooldown: 75, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(2),
		minRange: 64, maxRange: 384,
		innerSplashRadius: 10, medianSplashRadius: 25, outerSplashRadius: 40,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 29: Longbolt_Missile
	{damageAmount: 20, damageBonus: 0, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 30: Yamato_Gun
	{damageAmount: 260, damageBonus: 0, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(15),
		minRange: 0, maxRange: 320,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 31: Nuclear_Strike
	{damageAmount: 600, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(5),
		minRange: 0, maxRange: 3,
		innerSplashRadius: 128, medianSplashRadius: 192, outerSplashRadius: 256,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 32: Lockdown
	{damageAmount: 0, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(4),
		minRange: 0, maxRange: 256,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 33: EMP_Shockwave
	{damageAmount: 0, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(8),
		minRange: 0, maxRange: 256,
		innerSplashRadius: 64, medianSplashRadius: 64, outerSplashRadius: 64,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 34: Irradiate
	{damageAmount: 250, damageBonus: 0, damageCooldown: 75, damageFactor: 1,
		damageType: DamageType(4), explosionType: ExplosionType(9),
		minRange: 0, maxRange: 288,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 35: Claws
	{damageAmount: 5, damageBonus: 1, damageCooldown: 8, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 15,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(10)},
	// 36: Claws_Devouring_One
	{damageAmount: 10, damageBonus: 1, damageCooldown: 8, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 15,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(10)},
	// 37: Claws_Infested_Kerrigan
	{damageAmount: 50, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 15,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(10)},
	// 38: Needle_Spines
	{damageAmount: 10, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(11)},
	// 39: Needle_Spines_Hunter_Killer
	{damageAmount: 20, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(11)},
	// 40: Kaiser_Blades
	{damageAmount: 20, damageBonus: 3, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 25,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(10)},
	// 41: Kaiser_Blades_Torrasque
	{damageAmount: 50, damageBonus: 3, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 25,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(10)},
	// 42: Toxic_Spores
	{damageAmount: 4, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 2,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(10)},
	// 43: Spines
	{damageAmount: 5, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 32,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 44: (skipped)
	{damageAmount: 0, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 45: (skipped)
	{damageAmount: 30, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 64,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(12)},
	// 46: Acid_Spore
	{damageAmount: 20, damageBonus: 2, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 256,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(12)},
	// 47: Acid_Spore_Kukulza
	{damageAmount: 40, damageBonus: 2, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 256,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(12)},
	// 48: Glave_Wurm
	{damageAmount: 9, damageBonus: 1, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 96,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(12)},
	// 49: Glave_Wurm_Kukulza
	{damageAmount: 18, damageBonus: 1, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 96,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(12)},
	// 50: (skipped)
	{damageAmount: 5, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(2),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 10, medianSplashRadius: 20, outerSplashRadius: 30,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(11)},
	// 51: (skipped)
	{damageAmount: 10, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(2),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 10, medianSplashRadius: 20, outerSplashRadius: 30,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(11)},
	// 52: Seeker_Spores
	{damageAmount: 15, damageBonus: 0, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 53: Subterranean_Tentacle
	{damageAmount: 40, damageBonus: 0, damageCooldown: 32, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 54: Suicide_Infested_Terran
	{damageAmount: 500, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(2),
		minRange: 0, maxRange: 3,
		innerSplashRadius: 20, medianSplashRadius: 40, outerSplashRadius: 60,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 55: Suicide_Scourge
	{damageAmount: 110, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 3,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 56: Parasite
	{damageAmount: 0, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(0), explosionType: ExplosionType(6),
		minRange: 0, maxRange: 384,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 57: Spawn_Broodlings
	{damageAmount: 0, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(0), explosionType: ExplosionType(7),
		minRange: 0, maxRange: 288,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 58: Ensnare
	{damageAmount: 0, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(0), explosionType: ExplosionType(10),
		minRange: 0, maxRange: 288,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 59: Dark_Swarm
	{damageAmount: 0, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(0), explosionType: ExplosionType(13),
		minRange: 0, maxRange: 288,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 60: Plague
	{damageAmount: 300, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(0), explosionType: ExplosionType(11),
		minRange: 0, maxRange: 288,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 61: Consume
	{damageAmount: 0, damageBonus: 0, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(0), explosionType: ExplosionType(14),
		minRange: 0, maxRange: 16,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 62: Particle_Beam
	{damageAmount: 5, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 32,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 63: (skipped)
	{damageAmount: 0, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(0),
		minRange: 0, maxRange: 10,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 64: Psi_Blades
	{damageAmount: 8, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 15,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 65: Psi_Blades_Fenix
	{damageAmount: 20, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 15,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 66: Phase_Disruptor
	{damageAmount: 20, damageBonus: 2, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 67: Phase_Disruptor_Fenix
	{damageAmount: 45, damageBonus: 2, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 68: (skipped)
	{damageAmount: 5, damageBonus: 1, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 96,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 69: Psi_Assault
	{damageAmount: 20, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 96,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 70: Psionic_Shockwave
	{damageAmount: 30, damageBonus: 3, damageCooldown: 20, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(3),
		minRange: 0, maxRange: 64,
		innerSplashRadius: 3, medianSplashRadius: 15, outerSplashRadius: 30,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 71: Psionic_Shockwave_TZ_Archon
	{damageAmount: 60, damageBonus: 3, damageCooldown: 20, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(3),
		minRange: 0, maxRange: 64,
		innerSplashRadius: 3, medianSplashRadius: 15, outerSplashRadius: 30,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 72: (skipped)
	{damageAmount: 4, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 32,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(14)},
	// 73: Dual_Photon_Blasters
	{damageAmount: 8, damageBonus: 1, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(14)},
	// 74: Anti_Matter_Missiles
	{damageAmount: 14, damageBonus: 1, damageCooldown: 22, damageFactor: 2,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(14)},
	// 75: Dual_Photon_Blasters_Mojo
	{damageAmount: 20, damageBonus: 1, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(14)},
	// 76: Anti_Matter_Missiles_Mojo
	{damageAmount: 28, damageBonus: 1, damageCooldown: 22, damageFactor: 2,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(14)},
	// 77: Phase_Disruptor_Cannon
	{damageAmount: 10, damageBonus: 1, damageCooldown: 45, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(14)},
	// 78: Phase_Disruptor_Cannon_Danimoth
	{damageAmount: 20, damageBonus: 1, damageCooldown: 45, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(14)},
	// 79: Pulse_Cannon
	{damageAmount: 6, damageBonus: 1, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(14)},
	// 80: STS_Photon_Cannon
	{damageAmount: 20, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 81: STA_Photon_Cannon
	{damageAmount: 20, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 82: Scarab
	{damageAmount: 100, damageBonus: 25, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(3),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 20, medianSplashRadius: 40, outerSplashRadius: 60,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(35)},
	// 83: Stasis_Field
	{damageAmount: 0, damageBonus: 1, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(0), explosionType: ExplosionType(12),
		minRange: 0, maxRange: 288,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 84: Psionic_Storm
	{damageAmount: 14, damageBonus: 1, damageCooldown: 45, damageFactor: 1,
		damageType: DamageType(4), explosionType: ExplosionType(2),
		minRange: 0, maxRange: 288,
		innerSplashRadius: 48, medianSplashRadius: 48, outerSplashRadius: 48,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 85: Warp_Blades_Zeratul
	{damageAmount: 100, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 15,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 86: Warp_Blades_Hero
	{damageAmount: 45, damageBonus: 1, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 15,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 87: (skipped)
	{damageAmount: 7, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 88: (skipped)
	{damageAmount: 7, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 89: (skipped)
	{damageAmount: 7, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 32,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 90: (skipped)
	{damageAmount: 7, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 91: (skipped)
	{damageAmount: 7, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 92: Platform_Laser_Battery
	{damageAmount: 7, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 224,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 93: Independant_Laser_Battery
	{damageAmount: 7, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 94: (skipped)
	{damageAmount: 4, damageBonus: 1, damageCooldown: 9, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(60)},
	// 95: (skipped)
	{damageAmount: 30, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 96: Twin_Autocannons_Floor_Trap
	{damageAmount: 10, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 97: Hellfire_Missile_Pack_Wall_Trap
	{damageAmount: 10, damageBonus: 1, damageCooldown: 22, damageFactor: 2,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 98: Flame_Thrower_Wall_Trap
	{damageAmount: 8, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(3),
		minRange: 0, maxRange: 64,
		innerSplashRadius: 15, medianSplashRadius: 20, outerSplashRadius: 25,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 99: Hellfire_Missile_Pack_Floor_Trap
	{damageAmount: 10, damageBonus: 1, damageCooldown: 22, damageFactor: 2,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(8)},
	// 100: Neutron_Flare
	{damageAmount: 5, damageBonus: 1, damageCooldown: 8, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(25),
		minRange: 0, maxRange: 160,
		innerSplashRadius: 5, medianSplashRadius: 50, outerSplashRadius: 100,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(14)},
	// 101: Disruption_Web
	{damageAmount: 0, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(4), explosionType: ExplosionType(17),
		minRange: 0, maxRange: 288,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 102: Restoration
	{damageAmount: 20, damageBonus: 0, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(4), explosionType: ExplosionType(16),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 103: Halo_Rockets
	{damageAmount: 6, damageBonus: 1, damageCooldown: 64, damageFactor: 2,
		damageType: DamageType(1), explosionType: ExplosionType(25),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 5, medianSplashRadius: 50, outerSplashRadius: 100,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(9)},
	// 104: Corrosive_Acid
	{damageAmount: 25, damageBonus: 2, damageCooldown: 100, damageFactor: 1,
		damageType: DamageType(1), explosionType: ExplosionType(18),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(12)},
	// 105: Mind_Control
	{damageAmount: 8, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(19),
		minRange: 0, maxRange: 256,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 106: Feedback
	{damageAmount: 8, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(4), explosionType: ExplosionType(20),
		minRange: 0, maxRange: 320,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 107: Optical_Flare
	{damageAmount: 8, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(0), explosionType: ExplosionType(21),
		minRange: 0, maxRange: 288,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 108: Maelstrom
	{damageAmount: 0, damageBonus: 1, damageCooldown: 1, damageFactor: 1,
		damageType: DamageType(0), explosionType: ExplosionType(22),
		minRange: 0, maxRange: 320,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(60)},
	// 109: Subterranean_Spines
	{damageAmount: 20, damageBonus: 2, damageCooldown: 37, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(3),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 20, medianSplashRadius: 20, outerSplashRadius: 20,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(11)},
	// 110: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 111: Warp_Blades
	{damageAmount: 40, damageBonus: 3, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 15,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(13)},
	// 112: C_10_Canister_Rifle_Samir_Duran
	{damageAmount: 25, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 113: C_10_Canister_Rifle_Infested_Duran
	{damageAmount: 25, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 114: Dual_Photon_Blasters_Artanis
	{damageAmount: 20, damageBonus: 1, damageCooldown: 30, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: true,
		upgradeType: UpgradeType(14)},
	// 115: Anti_Matter_Missiles_Artanis
	{damageAmount: 28, damageBonus: 1, damageCooldown: 22, damageFactor: 2,
		damageType: DamageType(1), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: false,
		upgradeType: UpgradeType(14)},
	// 116: C_10_Canister_Rifle_Alexei_Stukov
	{damageAmount: 30, damageBonus: 1, damageCooldown: 22, damageFactor: 1,
		damageType: DamageType(2), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 192,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 117: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 118: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 119: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 120: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 121: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 122: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 123: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 124: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 125: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 126: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 127: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 128: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 129: (skipped)
	{damageAmount: 6, damageBonus: 1, damageCooldown: 15, damageFactor: 1,
		damageType: DamageType(3), explosionType: ExplosionType(1),
		minRange: 0, maxRange: 128,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: true, targetsGround: true,
		upgradeType: UpgradeType(7)},
	// 130: None
	{damageAmount: 0, damageBonus: 0, damageCooldown: 0, damageFactor: 0,
		damageType: DamageType(5), explosionType: ExplosionType(0),
		minRange: 0, maxRange: 0,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: false,
		upgradeType: UpgradeType(61)},
	// 131: Unknown
	{damageAmount: 0, damageBonus: 0, damageCooldown: 0, damageFactor: 0,
		damageType: DamageType(6), explosionType: ExplosionType(26),
		minRange: 0, maxRange: 0,
		innerSplashRadius: 0, medianSplashRadius: 0, outerSplashRadius: 0,
		targetsAir: false, targetsGround: false,
		upgradeType: UpgradeType(62)},
}
