package bwapi

// weaponTypeData holds static properties for a WeaponType.
type weaponTypeData struct {
	damageAmount       int
	damageBonus        int
	damageCooldown     int
	damageFactor       int
	damageType         DamageType
	explosionType      ExplosionType
	minRange           int
	maxRange           int
	innerSplashRadius  int
	medianSplashRadius int
	outerSplashRadius  int
	targetsAir         bool
	targetsGround      bool
	upgradeType        UpgradeType
}

// weaponTypeTable is a lookup table of static weapon type data, indexed by WeaponType ID.
// Populated from fullWeaponTypeTable (generated by gen_weapon_types.py).
var weaponTypeTable [132]weaponTypeData

func init() {
	for i, d := range fullWeaponTypeTable {
		weaponTypeTable[i] = weaponTypeData{
			damageAmount:       int(d.damageAmount),
			damageBonus:        int(d.damageBonus),
			damageCooldown:     int(d.damageCooldown),
			damageFactor:       int(d.damageFactor),
			damageType:         d.damageType,
			explosionType:      d.explosionType,
			minRange:           int(d.minRange),
			maxRange:           int(d.maxRange),
			innerSplashRadius:  int(d.innerSplashRadius),
			medianSplashRadius: int(d.medianSplashRadius),
			outerSplashRadius:  int(d.outerSplashRadius),
			targetsAir:         d.targetsAir,
			targetsGround:      d.targetsGround,
			upgradeType:        d.upgradeType,
		}
	}
}

func wtInRange(wt WeaponType) bool {
	return wt >= 0 && int(wt) < len(weaponTypeTable)
}

// DamageAmount returns the base damage dealt per attack.
func (wt WeaponType) DamageAmount() int {
	if !wtInRange(wt) {
		return 0
	}
	return weaponTypeTable[wt].damageAmount
}

// DamageBonus returns the bonus damage per upgrade level.
func (wt WeaponType) DamageBonus() int {
	if !wtInRange(wt) {
		return 0
	}
	return weaponTypeTable[wt].damageBonus
}

// DamageCooldown returns the number of frames between attacks.
func (wt WeaponType) DamageCooldown() int {
	if !wtInRange(wt) {
		return 0
	}
	return weaponTypeTable[wt].damageCooldown
}

// DamageFactor returns the damage multiplier (number of hits per attack).
func (wt WeaponType) DamageFactor() int {
	if !wtInRange(wt) {
		return 0
	}
	return weaponTypeTable[wt].damageFactor
}

// GetDamageType returns the DamageType of this weapon (Normal, Explosive, Concussive, etc.).
func (wt WeaponType) GetDamageType() DamageType {
	if !wtInRange(wt) {
		return DamageTypeNone
	}
	return weaponTypeTable[wt].damageType
}

// GetExplosionType returns the ExplosionType of this weapon.
func (wt WeaponType) GetExplosionType() ExplosionType {
	if !wtInRange(wt) {
		return ExplosionTypeNone
	}
	return weaponTypeTable[wt].explosionType
}

// MinRange returns the minimum attack range in pixels.
func (wt WeaponType) MinRange() int {
	if !wtInRange(wt) {
		return 0
	}
	return weaponTypeTable[wt].minRange
}

// MaxRange returns the maximum attack range in pixels.
func (wt WeaponType) MaxRange() int {
	if !wtInRange(wt) {
		return 0
	}
	return weaponTypeTable[wt].maxRange
}

// InnerSplashRadius returns the inner splash damage radius in pixels.
func (wt WeaponType) InnerSplashRadius() int {
	if !wtInRange(wt) {
		return 0
	}
	return weaponTypeTable[wt].innerSplashRadius
}

// MedianSplashRadius returns the median splash damage radius in pixels.
func (wt WeaponType) MedianSplashRadius() int {
	if !wtInRange(wt) {
		return 0
	}
	return weaponTypeTable[wt].medianSplashRadius
}

// OuterSplashRadius returns the outer splash damage radius in pixels.
func (wt WeaponType) OuterSplashRadius() int {
	if !wtInRange(wt) {
		return 0
	}
	return weaponTypeTable[wt].outerSplashRadius
}

// TargetsAir returns whether this weapon can target air units.
func (wt WeaponType) TargetsAir() bool {
	if !wtInRange(wt) {
		return false
	}
	return weaponTypeTable[wt].targetsAir
}

// TargetsGround returns whether this weapon can target ground units.
func (wt WeaponType) TargetsGround() bool {
	if !wtInRange(wt) {
		return false
	}
	return weaponTypeTable[wt].targetsGround
}

// GetUpgradeType returns the UpgradeType that increases this weapon's damage.
func (wt WeaponType) GetUpgradeType() UpgradeType {
	if !wtInRange(wt) {
		return UpgradeTypeNone
	}
	return weaponTypeTable[wt].upgradeType
}
